[package]
name = "probable"
version = "0.1.0"
edition = "2021"

[dependencies]
bit-vec = "0.6"
xxhash-rust = { version = "0.8", features = ["xxh3"] }

[dev-dependencies]
rand = "0.8"
criterion = "0.5"

[[bench]]
name = "lookup"
harness = false